name: Release

on: workflow_dispatch
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C target-feature=+crt-static


jobs:
  release:
    name: Publish release
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --target x86_64-unknown-linux-gnu --release --verbose && mv ./target/x86_64-unknown-linux-gnu/release/sniprun .

    - name: upload to releases
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sniprun
        tag: ${{github.ref}}
        overwrite: false
        body: "This release and associated artifacts were created by Github Action. See the changelog [here](https://github.com/michaelb/sniprun/blob/master/CHANGELOG.md)."
